<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="JayNits-MBP.attlocal.net" ignored="3" name="Default test" tests="1" failures="1" timestamp="23 Jul 2021 17:28:00 GMT" time="28.087" errors="0">
  <testcase name="testDepositAmountAndWithdrawlForDynamicCustomer" time="27.985" classname="UIAPI.Testing.CustomerTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="-1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: -1
at java.util.ArrayList.elementData(ArrayList.java:422)
at java.util.ArrayList.get(ArrayList.java:435)
at UIAPI.Testing.DepositHelper.getTransactionRow(DepositHelper.java:122)
at UIAPI.Testing.CustomerTest.testDepositAmountAndWithdrawlForDynamicCustomer(CustomerTest.java:142)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testDepositAmountAndWithdrawlForDynamicCustomer -->
  <testcase name="testDepositAmountForFirstCustomer" time="0.0" classname="UIAPI.Testing.CustomerTest">
    <ignored/>
  </testcase> <!-- testDepositAmountForFirstCustomer -->
  <testcase name="testDepositAmountForEachCustomer" time="0.0" classname="UIAPI.Testing.CustomerTest">
    <ignored/>
  </testcase> <!-- testDepositAmountForEachCustomer -->
  <testcase name="testDepositAmountAndWithdrawlForFirstCustomer" time="0.0" classname="UIAPI.Testing.CustomerTest">
    <ignored/>
  </testcase> <!-- testDepositAmountAndWithdrawlForFirstCustomer -->
</testsuite> <!-- Default test -->
